# Generated by Django 4.1.1 on 2022-09-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('ST', 'Starters'), ('MV', 'Movers'), ('FL', 'Flyers'), ('KT', 'KET'), ('PT', 'PET'), ('FC', 'FCE')], default='ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default='male', max_length=1)),
                ('adress', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='profile_pics/')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default='male', max_length=1)),
                ('adress', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='profile_pics/')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default='male', max_length=1)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='profile_pics/')),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fee', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.clss')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.course')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.parent')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.period')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('lesson_title', models.CharField(max_length=15)),
                ('lesson_description', models.CharField(max_length=500)),
                ('lesson_link', models.URLField(max_length=500)),
                ('lesson_preclass', models.URLField(max_length=500)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.clss')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.period')),
                ('teachers', models.ManyToManyField(default=False, to='towerweb.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='clss',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.course'),
        ),
        migrations.AddField(
            model_name='clss',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.period'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent'), ('SK', 'Sick'), ('LV', 'Leave')], default='PR', max_length=2)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.clss')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towerweb.lesson')),
                ('student', models.ManyToManyField(to='towerweb.student')),
            ],
        ),
    ]
